global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

clusterGroup:
  name: devel
  isHubCluster: false
  clusterName: wh-devel

  namespaces:
    - stackrox
    - policies
    - rhacs-operator
  
  subscriptions:
  - name: rhacs-operator  #packageName
    namespace: openshift-operators # operator namespace
    channel: rhacs-3.68
    csv: rhacs-operator.v3.68.1

  - name: openshift-pipelines-operator-rh
    csv: redhat-openshift-pipelines.v1.5.2

  - name: quay-bridge-operator
    namespace: openshift-operators
    channel: stable-3.6
    csv: quay-bridge-operator.v3.6.6

  projects:
    - secured
    - devel

  applications:
  - name: acs-secured
    namespace: stackrox
    project: secured
    path: common/acs/secured

  - name: pipelines
    namespace: devsecops-ci
    project: devel
    path: charts/hub/pipelines

  - name: quay-integration
    namespace: openshift-operators
    project: secured
    path: charts/region/quay

