clusterGroup:
  name: hub
  isHubCluster: true

  namespaces:    
  - open-cluster-management
  - vault
  - golang-external-secrets
  - config-demo
  - rhacs-operator
  - stackrox
  - devsecops-ci
  - openshift-storage
  - quay-enterprise
  
  subscriptions:  #name -> packageName
  - name: advanced-cluster-management
    namespace: open-cluster-management
    channel: release-2.4
    csv: advanced-cluster-management.v2.4.1

  - name: rhacs-operator  #packageName
    namespace: openshift-operators # operator namespace
    channel: rhacs-3.68
    csv: rhacs-operator.v3.68.1

  - name: openshift-pipelines-operator-rh
    csv: redhat-openshift-pipelines.v1.5.2

  - name: odf-operator
    namespace: openshift-storage
    channel: stable-4.10
    csv: odf-operator.v4.10.1

  - name: quay-operator
    namespace: openshift-operators
    channel: stable-3.6
    csv: quay-operator.v3.6.4

# add the top level 
# OpenShiftGitOps
  projects:   
  - hub
  - config-demo
  - golang-external-secrets

  applications:  
  - name: acm   #aibitary
    namespace: open-cluster-management
    project: hub
    path: common/acm
    ignoreDifferences:
    - group: internal.open-cluster-management.io
      kind: ManagedClusterInfo
      jsonPointers:
        - /spec/loggingCA

  - name: acs-central
    namespace: stackrox
    project: hub
    path: common/acs/central

  - name: acs-secured
    namespace: stackrox
    project: hub
    path: common/acs/secured

  - name: vault
    namespace: vault
    project: hub
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: v0.19.0
    overrides:
    - name: global.openshift
      value: "true"
    - name: injector.enabled
      value: "false"
    - name: ui.enabled
      value: "true"
    - name: ui.serviceType
      value: LoadBalancer
    - name: server.route.enabled
      value: "true"
    - name: server.route.host
      value: null
    - name: server.route.tls.termination
      value: edge
    - name: server.image.repository
      value: "registry.connect.redhat.com/hashicorp/vault"
    - name: server.image.tag
      value: "1.9.2-ubi"

  - name: golang-external-secrets
    namespace: golang-external-secrets
    project: golang-external-secrets
    path: common/golang-external-secrets

  - name: pipelines
    namespace: devsecops-ci
    project: hub
    path: charts/hub/pipelines

  - name: cli-tools
    namespace: openshift
    project: hub
    path: charts/hub/cli-tools

  - name: storage
    namespace: openshift-storage
    project: hub
    path: charts/hub/cephobjectstore

  - name: quay-registry
    namespace: quay-enterprise
    project: hub
    path: charts/hub/quay

  - name: config-demo
    namespace: config-demo
    project: config-demo
    path: charts/all/config-demo

  - name: acs-integrations
    namespace: stackrox
    project: hub
    path: charts/hub/acs

  managedClusterGroups:
  - name: devel
    helmOverrides:
    - name: clusterGroup.isHubCluster
      value: "false"
    clusterSelector:
      matchLabels:
        clusterGroup: devel
      matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift

  - name: secured
    helmOverrides:
    - name: clusterGroup.isHubCluster
      value: "false"
    clusterSelector:
      matchLabels:
        clusterGroup: secured
      matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift


# I don't think this is needed but let's check
#main:
#  clusterGroupName: hub

#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#  - name: pipelines
#    namespace: production
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: stable
#    overrides:
#    - name: myparam
#      value: myparam
#
#  - name: pipelines
#    namespace: staging
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: main
#
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#  - name: vendor-app
#    namespace: default
#    project: vendor
#    path: path/to/myapp
#    repoURL: https://github.com/vendor/applications.git
#    targetRevision: main

#  managedSites:
#  - name: factory
#    # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
#    targetRevision: main
#    path: applications/factory
#    helmOverrides:
#    - name: site.isHubCluster
#      value: false
#    clusterSelector:
#      matchExpressions:
#      - key: vendor
#        operator: In
#        values:
#          - OpenShift
