quay:
  namespace: quay-enterprise
  adminuser: quayadmin
  component:
    - name: clair
      managed: true
    - name: horizontalpodautoscaler
      managed: true
    - name: mirror
      managed: true
    - name: monitoring
      managed: true
    - name: postgres  
      managed: true 
    - name: redis 
      managed: true 
    - name: objectstorage 
      managed: true 
    - name: route 
      managed: true 
    - name: tls 
      managed: true
  configBundleSecret:
    deploy: true
    name: quay-init-config-bundle-secret

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest

global:
  hub:
    clustername: NAME
    domain: DOMAIN

  quay:
    account: quayadmin
    password: quayadmin123
    email: quayadmin@example.com